# Generated by Django 3.2.7 on 2022-07-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='owner_email',
            field=models.CharField(default='', max_length=30),
        ),
    ]
