# Generated by Django 3.2.7 on 2022-07-15 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carRentapp', '0002_tbl_booking_owner_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_driverBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_email', models.CharField(default='', max_length=30)),
                ('date', models.CharField(default='', max_length=30)),
                ('fromdate', models.CharField(default='', max_length=30)),
                ('todate', models.CharField(default='', max_length=30)),
                ('hrs', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('buyer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carRentapp.tbl_user')),
            ],
        ),
    ]
