# Generated by Django 3.2.7 on 2022-07-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRentapp', '0003_tbl_driverbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_driverbook',
            name='driver_phone',
            field=models.CharField(default='', max_length=30),
        ),
    ]
