# Generated by Django 3.2.7 on 2022-07-15 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carRentapp', '0004_tbl_driverbook_driver_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_email', models.CharField(default='', max_length=30)),
                ('subject', models.CharField(default='', max_length=30)),
                ('description', models.CharField(default='', max_length=30)),
                ('location', models.CharField(default='', max_length=30)),
                ('date', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('reply', models.CharField(default='', max_length=30)),
                ('buyer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carRentapp.tbl_user')),
            ],
        ),
    ]
